### PR TITLE
Use `CaseInsensitiveString` for `Headers`

### PR DESCRIPTION
**Pull request by joneshf**
Re: #136

Following the discussion in the above issue, this converts from `Object String` to `Map CaseInsensitiveString String`. Let me know if anything should be done differently.

Also addresses part of #113.

### CODE REVIEW

**Comment by cprussin** [comment]
CI is broken right now, I need to fix it, so please ignore the failures... sorry about that!

**Comment by cprussin** [comment]
@joneshf Sweet!  This is really great, thanks a bunch!

Just one question, I don't think there's any value any more in making `Headers` a `newtype`.  The only reason it was originally a `newtype` was so that it could have an instance of `Lookup` that did case-insensitive lookup, but now that `Headers` is a `Map CaseInsensitiveString String` there's no reason to have a unique instance.  Thoughts?

**Comment by joneshf** [comment]
Sounds good to me.

**Comment by joneshf** [comment]
Eh, most of the tests in `Test.HTTPure.HeadersSpec` will break:

```
1) HTTPure Headers show is a string representing the headers in HTTP format
  "(fromFoldable [(Tuple (CaseInsensitiveString \"Test1\") \"1\"),(Tuple (CaseInsensitiveString \"Test2\") \"2\")])" ≠ "Test1: 1\nTest2: 2\n\n"
2) HTTPure Headers append when there is a duplicated key uses the last appended value
  (fromFoldable [(Tuple (CaseInsensitiveString "Test") "foo")]) ≠ (fromFoldable [(Tuple (CaseInsensitiveString "Test") "bar")])
3) HTTPure Headers empty is an empty Map in an empty Headers
  "(fromFoldable [])" ≠ "\n"
4) HTTPure Headers header creates a singleton Headers
  "(fromFoldable [(Tuple (CaseInsensitiveString \"X-Test\") \"test\")])" ≠ "X-Test: test\n\n"
5) HTTPure Integration runs the middleware example
  "middleware" ≠ "router"
```

Some of this is the different behavior of `Show` and others are different behavior for `Semigroup`. Still worth it.

**Comment by cprussin** [comment]
Ah, right. I'd forgotten about those differences. Thank you for checking it out!

**Comment by joneshf** [comment]
> Still worth it.

Sorry, this was supposed to be, "Still worth it?"

**Comment by cprussin** [comment]
I think that we could clean up these APIs a bit and get rid of the newtype, but I think it's out of scope for this change.  So let's go ahead and merge this and I'll add a separate ticket to remove the newtype.

**Pull request merged**
