### PR TITLE
Add spago configuration

### PR DESCRIPTION
**Pull request by drewolson**
Are you interested in using `spago` for development now?

I generated a `spago.dhall` from your existing `psc-package.json`, upgraded to the latest set and added `docs/**/*.purs` to the path. Now `spago build` and `spago test` "just work" (though my test runs are flaky locally).

Let me know if this is something you're interesting in, `spago` seems to be the direction the community is moving.

### CODE REVIEW

**Comment by cprussin** [comment]
I'm not opposed to this at all, but I haven't kept a close pulse on things in the PS packaging world recently.  Last I was in the loop it didn't seem clear where things would go once bower locked down publishing, and I wasn't under the impression that spago was right for libraries.  Can you comment or link me to anything relevant?

**Comment by drewolson** [comment]
The best references I have are [this discourse thread](https://discourse.purescript.org/t/the-bower-registry-is-no-longer-accepting-package-submissions/1103/15) and these two [merged](https://github.com/purescript/purescript.github.io/pull/138) [PRs]( https://github.com/purescript/documentation/pull/286) making `spago` the default recommended build tool.

**Comment by cprussin** [comment]
Hmm, I'm still unclear on how Spago should be used for packaging libraries (of course using it as a build tool for apps makes sense).  Specifically, what does the publishing process look like now?  Does this mean that every publish needs to come with patch to the package set?  Presumably that should have been happening before, but is the package set now the only way to consume the lib?

**Comment by drewolson** [comment]
Here's my understanding of the current situation:

* `spago` is the new recommended tool for building applications and libraries
* As of now, `spago` can facilitate publishing new releases by calling out to `pulp`, however
* The `bower` registry has been deprecated and is no longer allowing new package submissions. Only existing packages can publish updates.
* Because of this, the core team is working on a new registry. They expect to have this registry act as the source of truth and store package artifacts, removing the dependency on `bower` completely
* Initially, there may be manual work (i.e. pull requests) to update the registry, but eventually this should be rolled into the `spago` tool

I _think_ I've got the current story correct. Things are definitely in a bit of flux now, and if you'd prefer to wait on something like this until stuff settles down, I think that makes sense.

**Comment by cprussin** [comment]
Got it, this is all very helpful.  Thanks for that context @drewolson.

I don't necessarily think we need to wait until things settle.  Spago is a great build tool so it doesn't hurt to have it set up while we wait for things to settle down.  I'll just need to make sure we re-publish httpure with whatever the new system is once it materializes.

**Pull request merged**
